# Generated by Django 3.0.5 on 2020-04-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200426_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
