# Generated by Django 3.0.5 on 2020-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(null=True, upload_to='home/static/home/images/'),
        ),
    ]
